"use client";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowUpRight, ArrowDown, Menu, X, Plus, Check } from "lucide-react";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";

const services = [
 {name:"Custom AI Solutions",short:"AI that works for you.",text:"Turn your knowledge, data, and ideas into intelligent tools. We build custom AI assistants and applications around the way your business actually works.",items:["AI agents & assistants","Knowledge & document search","Custom AI applications"]},
 {name:"Automations",short:"Less busywork. More business.",text:"Give your team its time back. Connect your tools, streamline repetitive tasks, and keep every lead moving from first touch to follow-up.",items:["CRM & lead workflows","App & API integrations","Operations automation"]},
 {name:"Motion Design & Video Editing",short:"Make every second count.",text:"Turn a scroll into a stop. From sharp social edits to expressive brand motion, we create content that makes your message impossible to miss.",items:["Reels & short-form video","Brand motion & explainers","Ad creatives & video editing"]},
 {name:"Social Media Marketing",short:"Attention with a purpose.",text:"Build a presence that does more than fill a feed. Align your strategy, content, and campaigns to reach the right people and turn interest into action.",items:["Social strategy & content","Campaign creative","Reporting & optimization"]}
];
const faqs = [
 ["Where should we start?","Start with the business problem. Tell us what takes too much time, where leads drop off, or what you want your brand to achieve. We’ll help define the most useful first step."],
 ["Can I work with you on just one service?","Yes. Bring us a focused AI build, a single automation, a video editing brief, or your social marketing needs. Services can also be combined into one coordinated project."],
 ["How much does a project cost?","Pricing depends on scope, integrations, content volume, and timeline. We define the deliverables and agree on the price before work begins."],
 ["How long does a project take?","A focused task and a custom AI application need different timelines. Once we understand your brief, we propose milestones and a realistic delivery schedule."],
 ["Will this work with the tools we already use?","We first review your existing tools and available integrations. We then recommend a practical approach and flag any platform limitations before the build."],
 ["What happens after launch?","We include a handover so you can use what we build. If you need ongoing maintenance, new content, or campaign optimization, we can scope continued support together."]
];

export default function Home(){
 const [menu,setMenu]=useState(false); const [service,setService]=useState("Not sure yet"); const [budget,setBudget]=useState(""); const [status,setStatus]=useState("idle"); const [error,setError]=useState(""); const [ref,setRef]=useState("");
 useEffect(()=>{ const els=document.querySelectorAll('.reveal'); const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:0.08});els.forEach(e=>io.observe(e));return()=>io.disconnect();},[]);
 function start(s:string){setService(s);setStatus("idle");setMenu(false);document.getElementById('contact')?.scrollIntoView({behavior:'smooth'});}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setStatus("sending");const data=new FormData(e.currentTarget);try{const res=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),email:data.get('email'),company:data.get('company'),message:data.get('message'),website:data.get('website'),service,budget})});const result=await res.json();if(!res.ok)throw new Error(result.error||"Something went wrong. Please try again.");setRef(result.reference);setStatus('success');}catch(err){setError(err instanceof Error?err.message:'Please try again.');setStatus('idle')}}
 return <>
 <a className="skip" href="#services">Skip to content</a>
 <header className="header"><a className="brand" href="#home" aria-label="NOSH AI Solutions home"><span className="brand-name">NOSH<span className="brand-star">✳</span></span><span className="brand-sub">AI SOLUTIONS</span></a><nav className={menu?'nav open':'nav'} aria-label="Main navigation"><a onClick={()=>setMenu(false)} href="#services">Services <ArrowDown size={15}/></a><a onClick={()=>setMenu(false)} href="#approach">Our approach</a><a onClick={()=>setMenu(false)} href="#about">About us</a></nav><button className="button dark header-cta" onClick={()=>start('Not sure yet')}>Let’s talk <ArrowUpRight size={18}/></button><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main>
 <section className="hero" id="home"><h1><span>SMARTER SYSTEMS.</span><span>STRONGER CONTENT.</span><span>UNSTOPPABLE BRANDS.</span></h1><div className="hero-bottom"><div className="hero-copy"><p>We build custom AI, automate the busywork, and create content that gets you noticed. One creative and technical partner. More room for your business to grow.</p><div className="button-row"><button className="button dark" onClick={()=>start('Not sure yet')}>Start your project <ArrowUpRight size={18}/></button><a className="button" href="#services">Explore services <ArrowDown size={16}/></a></div></div><div className="hero-showcase"><div className="image-stack"><img className="back-image" src="/assets/alice.png" alt="Editorial website design inspiration"/><img className="front-image" src="/assets/museum.webp" alt="Bold typography and imagery from the Grigoletti reference project"/></div><div className="showcase-caption"><span>VISUAL INSPIRATION</span><a href="https://grigoletti.ch/en/" target="_blank" rel="noreferrer">GRIGOLETTI <ArrowUpRight size={12}/></a></div></div></div><div className="hero-foot"><span>INTELLIGENCE MEETS CREATIVITY</span><span>SCROLL TO DISCOVER <ArrowDown size={13}/></span></div></section>
 <section className="services dark-section" id="services"><div className="section-top reveal"><h2>How we can<br/>help you</h2><div className="section-intro"><span className="eyebrow">01 / SERVICES</span><p>Too many tools. Too much busywork.<br/>Not enough momentum.</p><p className="muted">We connect technology and creativity to help your business work smarter and show up stronger.</p></div></div><div className="services-grid">{services.map((s,i)=><article className="service reveal" key={s.name}><span className="service-num">0{i+1}.</span><h3>{s.name}</h3><p>{s.text}</p><div className="service-list">{s.items.map((item,j)=><div key={item}><span>0{j+1}</span>{item}</div>)}</div><button className="text-link" onClick={()=>start(s.name)}>Let’s build it <ArrowUpRight size={20}/></button></article>)}</div></section>
 <section className="approach" id="approach"><div className="section-top reveal"><h2>From ambition<br/>to action.</h2><div className="section-intro"><span className="eyebrow">02 / THE APPROACH</span><p>A clear plan. A connected team.<br/>A useful result.</p><p className="muted">Start with one challenge. Build what matters. Keep improving.</p></div></div><div className="process-grid">{[['Discover','Find the right opportunity.','We look at your goals, audience, and workflow to identify where AI, automation, or better content can make a difference.'],['Create','Build with purpose.','We turn the plan into working systems and compelling creative, with clear milestones and space for your feedback.'],['Launch','Put it into motion.','We test, refine, and launch with a clear handover. Then we help you decide what to improve or build next.']].map((p,i)=><article className="process reveal" key={p[0]}><div className="process-head"><span>0{i+1}</span><ArrowUpRight/></div><h3>{p[0]}</h3><h4>{p[1]}</h4><p>{p[2]}</p></article>)}</div><div className="approach-cta reveal"><p>Have the ambition, but not the brief?</p><button className="button dark" onClick={()=>start('Not sure yet')}>Find your starting point <ArrowUpRight size={18}/></button></div></section>
 <section className="about dark-section" id="about"><div className="about-intro reveal"><span className="eyebrow">03 / ABOUT NOSH</span><h2>Technical minds.<br/>Creative instincts.</h2><p>Great technology should make business simpler. Great creative should make people care. At NOSH AI Solutions, we bring both together.</p><p className="muted">We’re your partner for the systems behind the scenes and the stories your audience sees. Every project starts with your business, your goals, and a clear reason to build.</p></div><div className="values">{[['Made for you.','Solutions built around your business, not a one-size-fits-all playbook.'],['Clear scope.','Deliverables, milestones, and pricing agreed before the work starts.'],['One conversation.','AI, automation, motion, and marketing working toward the same goal.'],['Built to keep going.','Practical handovers and a path for ongoing improvement.']].map(v=><div className="value reveal" key={v[0]}><Plus size={20}/><div><h3>{v[0]}</h3><p>{v[1]}</p></div></div>)}</div></section>
 <section className="faq" id="faq"><div className="faq-title reveal"><span className="eyebrow">04 / GOOD QUESTIONS</span><h2>A little clarity.<br/>Before we begin.</h2></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem key={q} value={q}><AccordionTrigger><span className="q-num">(0{i+1})</span><span>{q}</span></AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <section className="contact dark-section" id="contact"><div className="contact-copy"><span className="eyebrow">05 / YOUR NEXT MOVE</span><h2>Let’s build<br/>what’s next.</h2><p>Tell us where you want to go.<br/>We’ll help you figure out how to get there.</p><div className="contact-note"><ArrowUpRight size={24}/><span>A focused first conversation.<br/>A clear next step.</span></div></div><div className="contact-form">{status==='success'?<div className="success" role="status"><Check size={42}/><h3>You're on the list.</h3><p>Your project inquiry has been saved. We’ll review your goals and use the email you provided to discuss the next step.</p><span className="eyebrow">REFERENCE / {ref}</span><button className="button light" onClick={()=>{setStatus('idle');setBudget('')}}>Send another inquiry <ArrowUpRight size={18}/></button></div>:<form onSubmit={submit}><fieldset><legend>What can we help you with?</legend><RadioGroup value={service} onValueChange={setService} className="service-options">{[...services.map(s=>s.name),'Not sure yet'].map((s,i)=><label className={service===s?'service-option selected':'service-option'} key={s}><RadioGroupItem value={s} id={'choice'+i}/><span>{s}</span></label>)}</RadioGroup></fieldset><div className="input-row"><label>Your name<input name="name" autoComplete="name" placeholder="Alex Morgan" maxLength={120} required/></label><label>Your email<input name="email" type="email" autoComplete="email" placeholder="alex@company.com" maxLength={254} required/></label></div><div className="input-row"><label>Company <span>(optional)</span><input name="company" autoComplete="organization" placeholder="Your business" maxLength={160}/></label><label>Budget range <span>(optional)</span><Select value={budget} onValueChange={setBudget}><SelectTrigger aria-label="Budget range" className="budget-select"><SelectValue placeholder="Let’s discuss"/></SelectTrigger><SelectContent>{['Under $1,000','$1,000–$5,000','$5,000–$10,000','$10,000+','Let’s discuss'].map(b=><SelectItem value={b} key={b}>{b}</SelectItem>)}</SelectContent></Select></label></div><label>What would you like to achieve?<textarea name="message" placeholder="The idea, the challenge, the big ambition…" required minLength={10} maxLength={5000} rows={3}/></label><div className="honey" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><p className="form-privacy">We’ll use these details to respond to your inquiry.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="button light submit" type="submit" disabled={status==='sending'}>{status==='sending'?'Sending…':'Let’s talk about your project'}<ArrowUpRight size={20}/></button></form>}</div></section>
 </main><footer><div className="footer-top"><a className="brand" href="#home"><span className="brand-name">NOSH<span className="brand-star">✳</span></span><span className="brand-sub">AI SOLUTIONS</span></a><p>Smarter systems. Stronger stories.</p><a className="back-top" href="#home">BACK TO TOP <ArrowUpRight size={16}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} NOSH AI Solutions</span><div><a href="#services">Services</a><a href="#about">About us</a><a href="#contact">Contact</a></div><span>INTELLIGENCE × CREATIVITY</span></div></footer>
 </>
}
